server {
  listen 80;
  server_name _;
  client_max_body_size 50m;

  root /usr/share/nginx/html;
  index index.html;

  location /api/ {
    proxy_pass http://api:8766;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location /assets/ {
    proxy_pass http://api:8766;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    expires 1y;
    add_header Cache-Control "public, immutable";
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
